# fly.toml app configuration file generated for notifybakc on 2024-03-08T21:08:01+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'notifybakc'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 50000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
